Jokes Chrome Extension/styles.css
=> Added styles for Jokes Chrome Extension

Jokes Chrome Extension/script.js
=> Added script.js for Jokes Chrome Extension

audioRecorder.py
=> Audio Recorder using Python

wordtopdf.py
=> word to pdf with python

General Store Management System/store.cpp
=> General Store Management System

Game/stone_paper_scissor.cpp
=> stone_paper_scissor.cpp

Game/guess_the_number.cpp
=> guess_the_number.cpp

Orphanage Management/orphanage.cpp
=> orphanage_management.cpp

Game/SnakeGame.cpp
A simple snake game in c++ in which the idea is not to erase the complete screen and print newly. On snake's movement it just erase the ending character (the tail of the snake) due to which the screen does not seem blinking. I have also added a classic mode where the snake gets killed when hit to the wall. It automatically adjusts if the window size changes. It only works in Windows OS because of the usage of windows.h header file.
=> Snake game in c++

Game/Ping-pong.py
=> Ping-pong.py

Game/Playing-cards.py
=> Playing-cards.py

School Management/school_management.py
=> school_management.py

Alarm Clock/alarm-clock.py
=> alarm-clock.py

image_compressor_py/README.md, image_compressor_py/script.py
Update regarding issue #78 .
I have added the code for this and has also created readme file for this.
=> Update regarding issue #78

QR Generator/QR_Generator.py
=> Python script for QR Code Generation

CC Validator/cc-validator.cpp
=> cc-validator.cpp

Random Quote Generator/README.md, Random Quote Generator/index.html, Random Quote Generator/quote.js, Random Quote Generator/script.js, Random Quote Generator/style.css
I have added the code for Random Quote Generator.
=> Create Random Quote Generator Project

Medical Website/styles.css
change in some style will appear when mouse pointer will point to navbar elements also after visting color of a link will change
=> added some style in navbar of medical website

Chat-App/utils/messages.js, Chat-App/utils/users.js
=> Update of Chat App

Chat-App/public/css/style.css, Chat-App/public/js/main.js
=> Complete code of Chat App

Analog Clock/index.html
Respected Sir, I added footer to nanalog clock index.html. Kindly accept the changes under hacktober fest.
=> Added copyright footer to analog clock index.html

Method/all_occurences.cpp
=> all_occurences.cpp

Method/palindrome_recursive.cpp
=> palindrome_recursive.cpp

30 days of Javascript/01 - JSDrumKit/index.html, 30 days of Javascript/01 - JSDrumKit/style.css, 30 days of Javascript/Readme.md
=> 30 days of javascript projects

Chat-App/public/chat.html, Chat-App/public/css/style.css, Chat-App/public/index.html
Respected sir(@PeanutCoffee ) please accept my changes under hacktoberfest.
=> Updated footer to the chat-app(hakctoberfest)

30 days of Javascript/03 - CSSVariablesWithJS/index.html, 30 days of Javascript/03 - CSSVariablesWithJS/main.js, 30 days of Javascript/03 - CSSVariablesWithJS/styles.css
=> css vars with js

30 days of Javascript/04 - ArrayCardioPart1/index.html, 30 days of Javascript/04 - ArrayCardioPart1/main.js
=> array cardio

30 days of Javascript/05 - FlexPanelGallery/index.html, 30 days of Javascript/05 - FlexPanelGallery/main.js, 30 days of Javascript/05 - FlexPanelGallery/styles.css
=> flex panel

30 days of Javascript/06 - ArrayCardioPartTwo/index.html, 30 days of Javascript/06 - ArrayCardioPartTwo/main.js
=> array cardio 2

30 days of Javascript/07 - FunWithHTMLCanvas/index.html, 30 days of Javascript/07 - FunWithHTMLCanvas/main.js
=> html canvas

Game/number-guess.py
=> Number-guess.py

Dice Game/dicee.html, Dice Game/index.js, Dice Game/styles.css
Signed-off-by: AbdulMoizKhan <abdulmoizkhan140@gmail.com>
=> added a reset button no need to refresh

Boston_Houding_Model/Model.py, Boston_Houding_Model/README.md
=> Added Boston Model

Random_Quote_Generator/app.js, Random_Quote_Generator/index.html, Random_Quote_Generator/styles.css
This is a Random Quote Generator Website that uses HTML , CSS and JavaScript , that basically displays shuffled quotes on being promted .
The styling has been done using a separately created CSS stylesheet .
A separate app.js file has been used to implement the required functionalities so as to make the page dynamic .
=> Added a Ranfom Quote Generator Website that uses HTML ,CSS and JavaScript .

image_Processing/imageProcessing.py
Thanks you for reviewing my code.
=> add image processing project that convert image colours

Painting App/index.html, Painting App/script.js, Painting App/style.css
I have built a Painting App, please merge my project under Hacktoberfest.
=> Painting App

Measurement_conversion/measurement-conversion.sql, Measurement_conversion/measurement-conversion/Styles.css, Measurement_conversion/measurement-conversion/area.php, Measurement_conversion/measurement-conversion/history.php, Measurement_conversion/measurement-conversion/includes/functions.php, Measurement_conversion/measurement-conversion/index.php, Measurement_conversion/measurement-conversion/length.php, Measurement_conversion/measurement-conversion/mass.php, Measurement_conversion/measurement-conversion/speed.php, Measurement_conversion/measurement-conversion/temperature.php, Measurement_conversion/measurement-conversion/volume.php
Measurement Conversion System using php and has a database using XAMPP and shows past conversions
=> Measurement Conversion System using php and has db
